### PR TITLE
For #2273 Fix path

### PR DESCRIPTION
**Pull request by mugitty**

### CODE REVIEW

**Comment by dustine32** [comment]
Thanks @mugitty! I'm actually running a local test of `go-site-2273-path-fix` with `validate.py rule` and `produce` right now and then will review if it succeeds. Quality control!

**Review by dustine32 — APPROVED** [review]
@mugitty Thanks for the quick fix! I confirmed that running `rule` and `produce` locally do not err out.

**Comment by dustine32** [comment]
@mugitty Merge away!

**Comment by mugitty** [comment]
Thanks for reviewing and testing

**Pull request merged**
