### PR TITLE
Use rst for readme

### PR DESCRIPTION
**Pull request by cmungall**
See #54

### CODE REVIEW

**Comment by diekhans** [comment]
can you do the same for prefixcommons-py, as it suffers from the same issue.

**Comment by dougli1sqrd** [comment]
I don't understand why pandoc would be running on a pip install? Wasn't the issue before one of using the wrong python version? Markdown really is a much nicer format.

**Comment by dougli1sqrd** [comment]
```
edouglass@Erics-MacBook-Pro:~/lbl$ brew uninstall pandoc
edouglass@Erics-MacBook-Pro:~/lbl$ pandoc
-bash: pandoc: command not found
Uninstalling /usr/local/Cellar/pandoc/1.19.2.1... (72 files, 116.8MB)
edouglass@Erics-MacBook-Pro:~/lbl$ python3 -m venv env
edouglass@Erics-MacBook-Pro:~/lbl$ . env/bin/activate
(env) edouglass@Erics-MacBook-Pro:~/lbl$ which pip
/Users/edouglass/lbl/env/bin/pip
(env) edouglass@Erics-MacBook-Pro:~/lbl$ which pip3
/Users/edouglass/lbl/env/bin/pip3
(env) edouglass@Erics-MacBook-Pro:~/lbl$ pip3 install ontobio==0.2.10
Collecting ontobio==0.2.10
  Using cached ontobio-0.2.10-py3-none-any.whl
Collecting requests (from ontobio==0.2.10)
  Using cached requests-2.18.1-py2.py3-none-any.whl
Collecting marshmallow (from ontobio==0.2.10)
  Using cached marshmallow-2.13.5-py2.py3-none-any.whl
Collecting scipy (from ontobio==0.2.10)
  Using cached scipy-0.19.1-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting prefixcommons (from ontobio==0.2.10)
  Using cached prefixcommons-0.1.3-py3-none-any.whl
Collecting pysolr (from ontobio==0.2.10)
  Using cached pysolr-3.6.0-py2.py3-none-any.whl
Collecting pyyaml (from ontobio==0.2.10)
Collecting cachier (from ontobio==0.2.10)
  Using cached cachier-1.2.1.tar.gz
Collecting networkx (from ontobio==0.2.10)
  Using cached networkx-1.11-py2.py3-none-any.whl
Collecting sparqlwrapper (from ontobio==0.2.10)
Collecting idna<2.6,>=2.5 (from requests->ontobio==0.2.10)
  Using cached idna-2.5-py2.py3-none-any.whl
Collecting urllib3<1.22,>=1.21.1 (from requests->ontobio==0.2.10)
  Using cached urllib3-1.21.1-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->ontobio==0.2.10)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->ontobio==0.2.10)
  Using cached certifi-2017.4.17-py2.py3-none-any.whl
Collecting numpy>=1.8.2 (from scipy->ontobio==0.2.10)
  Using cached numpy-1.13.0-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting watchdog (from cachier->ontobio==0.2.10)
Collecting portalocker (from cachier->ontobio==0.2.10)
  Using cached portalocker-1.1.0-py2.py3-none-any.whl
Collecting decorator>=3.4.0 (from networkx->ontobio==0.2.10)
  Using cached decorator-4.0.11-py2.py3-none-any.whl
Collecting rdflib>=4.0 (from sparqlwrapper->ontobio==0.2.10)
  Using cached rdflib-4.2.2-py3-none-any.whl
Collecting pathtools>=0.1.1 (from watchdog->cachier->ontobio==0.2.10)
Collecting argh>=0.24.1 (from watchdog->cachier->ontobio==0.2.10)
  Using cached argh-0.26.2-py2.py3-none-any.whl
Collecting pyparsing (from rdflib>=4.0->sparqlwrapper->ontobio==0.2.10)
  Using cached pyparsing-2.2.0-py2.py3-none-any.whl
Collecting isodate (from rdflib>=4.0->sparqlwrapper->ontobio==0.2.10)
Installing collected packages: idna, urllib3, chardet, certifi, requests, marshmallow, numpy, scipy, pathtools, pyyaml, argh, watchdog, portalocker, cachier, prefixcommons, pysolr, decorator, networkx, pyparsing, isodate, rdflib, sparqlwrapper, ontobio
  Running setup.py install for cachier ... done
Successfully installed argh-0.26.2 cachier-1.2.1 certifi-2017.4.17 chardet-3.0.4 decorator-4.0.11 idna-2.5 isodate-0.5.4 marshmallow-2.13.5 networkx-1.11 numpy-1.13.0 ontobio-0.2.10 pathtools-0.1.2 portalocker-1.1.0 prefixcommons-0.1.3 pyparsing-2.2.0 pysolr-3.6.0 pyyaml-3.12 rdflib-4.2.2 requests-2.18.1 scipy-0.19.1 sparqlwrapper-1.8.0 urllib3-1.21.1 watchdog-0.8.3
```
Is there something I'm missing from your (@diekhans) environment that requires you to have pandoc to install ontobio?

**Comment by diekhans** [comment]
The trigger was the wrong version of python, but this isn't the
underlying problem.

pip2 install skips the ontobio-0.2.10-py3-none-any.whl in pypi
and installs the ontobio-0.2.10.tar.gz, which always tries to
run pandoc.  However, there is no README.md in the extracted tmp
directory, so it generates the obscure error.

It turns out that the source tar ontobio-0.2.10.tar.gz will
not install with pip3 either.  Same with prefixcommons.

do a
  pip-3.6 install prefixcommons-pydist/prefixcommons-0.1.3.tar.gz
to see the problem.


I figured all this out when trying to create a setup that checked
for python3.  Only goal is to have a clear error message.

Solutions I though of were:
  1) Generate the README.rst at build time and include it in
     the source build.  This way the heavy weight generation
     is only on the builder's side.  This seems the best approach if
     sticking with MD, as it means you can require pandoc and not
     have the sometimes RST sometimes MD logic.
  2) Don't generate the sdist build at all.  Not sure of the
     downside; but would probably want to have setup generate an
     error on setup sdist so people wanting to contribute do not
     have to figure all of this out again.
  3) Switch to RST.

**Comment by dougli1sqrd** [comment]
Which directory should I run your command that duplicates the error? I don't have a tar.gz of prefixcommons anywhere. Is this in the repository of prefixcommons?

**Comment by cmungall** [comment]
I heart markdown too, but rst is more idiomatic for python, and it's just the README - the source for the readthedocs is already in RST

**Comment by diekhans** [comment]
if you do a setup.py sdist you get the .tar.gz; it's also on pypi.

**Pull request merged**
