### PR TITLE
Filter for None before calling join in golr_query

### PR DESCRIPTION
**Pull request by deepakunni3**
This bug was causing some of the Golr queries to fail

### CODE REVIEW

**Comment by kshefchek** [comment]
Is this something that would be better fixed upstream - do we know where the nulls are coming from?

**Comment by deepakunni3** [comment]
The nulls are showing up when we map the GOlr fields with AmiGO GOlr fields.
The field mapping contains None, which then finds its way into `select_fields`

**Comment by kshefchek** [comment]
makes sense, I haven't taken a close look but my intuition is that we could filter these out when creating/appending items to the list, or adding this filter right after all items have been added

**Comment by deepakunni3** [comment]
Yup, makes sense. I think the entirety of golr_query is due a sanity check.
Because we should handle empty lists and `None` values properly before sending it to Solr.
There are bugs popping up when certain fields are None and they are passed through.

For example, 
- `fq=subject_taxon_closure:""` yields no result
- `fq=subject_taxon_closure:"None"` yields no result

**Pull request merged**
