### PR TITLE
solr search query add support for filtering based on equivalent curie prefix, leaf nodes

### PR DESCRIPTION
**Pull request by kshefchek**
Adds support for filtering in/out a prefix in a equivalent curie as well as filtering for only leaf nodes. See https://github.com/biolink/biolink-api/issues/368

### CODE REVIEW

**Comment by kshefchek** [comment]
@iimpulse could you review?

**Review by iimpulse — APPROVED** [review]

**Comment by iimpulse** [comment]
out of curiosity do we have any tests?

**Comment by kshefchek** [comment]
there are no tests, a little challenging to mock the solr request, but we could mock the solr response to make sure the _process_autocomplete_results fx is working as expected

**Comment by iimpulse** [comment]
I was thinking more on the golr query that it builds that fq properly or that complex equivalent stuff correctly, less so on a functional or integration

**Comment by kshefchek** [comment]
ah yes, that's a good idea, I'll add it before merging

**Comment by kshefchek** [comment]
@iimpulse tests added with add608c

**Pull request merged**
