### PR TITLE
Issue 544 rulesets

### PR DESCRIPTION
**Pull request by dougli1sqrd**
For https://github.com/biolink/ontobio/issues/544

### CODE REVIEW

**Comment by kltm** [comment]
Looks good to me so far.
Is the idea that if you declare rules, but don't specify, they all run, or does one need to be explicit?
I'll leave it to @dustine32 to do final review and merge.

**Review by dustine32 — APPROVED** [review]
Yeah this looks pretty cool.

**Comment by dougli1sqrd** [comment]
Yeah, in ontobio-parse-assocs if no rules are specified, then none are run. You can pass in the string "all" to set all the rules, otherwise, it just uses whatever set you pass in via repeated `-l <N>`

**Comment by kltm** [comment]
Okay--sounds good. Looks good to me.

**Pull request merged**
