### PR TITLE
Convert relations to has_primary_input for #613

### PR DESCRIPTION
**Pull request by dustine32**
For #613.

### CODE REVIEW

**Comment by kltm** [comment]
Why are
`     "transports_or_maintains_localization_of": "RO:0004009",`
and
`     "has primary input": "http://purl.obolibrary.org/obo/RO_0004009",`
so different?

**Comment by kltm** [comment]
More discussion on ticket. Will merge.

**Comment by dustine32** [comment]
@kltm Noting that the first line `"transports_or_maintains_localization_of": "RO:0004009",` is in a dictionary lookup used to transform relations to different relations, e.g. `transports_or_maintains_localization_of` -> `has_primary_input`, in a `gocamgen` annotation-to-model translation context. Whereas the second line `"has primary input": "http://purl.obolibrary.org/obo/RO_0004009",` is the dictionary lookup in `ontobio` used for storing the actual relation label -> CURIE data (essentially, a subset copy of RO). Adding these relations to the latter lookup green-lights their acceptance by the `ontobio` parsers/writers that use `relations.py`.

**Comment by dustine32** [comment]
Linking to explanation about why both `imports` and `exports` are being converted to `has_primary_input`: https://github.com/biolink/ontobio/issues/613#issuecomment-1061204878

**Pull request merged**
