### PR TITLE
Set user-agent for requests made by ontobio

### PR DESCRIPTION
**Pull request by deepakunni3**
This PR adds `User-Agent` to headers of all HTTP requests made by Ontobio. See #190 

This PR also tidies up the way pysolr is instantiated in `golr_query.py`.

### CODE REVIEW

**Comment by deepakunni3** [comment]
An example of the 'User-Agent' in request header:

`ontobio 1.1.4 [ontobio.golr.golr_query] (ontobio/1.1.4)`

**Comment by kltm** [comment]
Looking at this, maybe we should have something a little more in line with a "standard": https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent

**Comment by deepakunni3** [comment]
Going by the recommendations,

User-Agent for Ontobio:
`ontobio/1.1.4 (ontobio.golr.golr_query)`

User-Agent for biolink-API -> Ontobio:
`ontobio/1.1.4 (ontobio.golr.golr_query) biolink-api/bd0abb4`

where `bd0abb4` is the commit-hash of biolink-API. This can be replaced with version when we start versioning the API.

Recommended User-Agent for any upstream tool using Ontobio:
`ontobio/1.1.4 (ontobio.golr.golr_query) <tool_name>/<version>`

**Comment by deepakunni3** [comment]
@kltm This is now ready for review

**Pull request merged**
