### PR TITLE
adds a proper shebang to common ontobio scripts

### PR DESCRIPTION
**Pull request by dougli1sqrd**

### CODE REVIEW

**Comment by kltm** [comment]
This does not immediately affect me/GO. Perhaps @deepakunni3 might have a thought?

**Comment by dougli1sqrd** [comment]
Shouldn't affect anything but the pipeline. Just throwing your way for some eyes.

**Comment by kltm** [comment]
Seems unlikely to break things.

**Comment by deepakunni3** [comment]
I know this is after the fact, but it doesn't affect anything. Much more neater this way.

**Pull request merged**
