### PR TITLE
For #2093

### PR DESCRIPTION
**Pull request by mugitty**

### CODE REVIEW

**Comment by mugitty** [comment]
@paudet has made some changes to the requirements.  I have to made additional changes. I will let you know when it is ready for review.

Thanks

**Comment by kltm** [comment]
@mugitty The user you want it: @pgaudet, not "Paudet"

**Comment by kltm** [comment]
@mugitty Updating your comment

**Comment by mugitty** [comment]
The code is ready for review, I have updated for the new requirements.

**Comment by kltm** [comment]
For #2093 -- to create link

**Comment by dustine32** [comment]
@mugitty Is this the `ontobio` change needed to update go-site's [Makefile-gaf-reprocess](https://github.com/geneontology/go-site/blob/master/scripts/Makefile-gaf-reprocess) to be used in the GO pipeline's "Temporary post filter" step? Sorry if I'm mixing this up with a slack convo we had last Thurs.

**Comment by dustine32** [comment]
@mugitty I'm mainly concerned with finding the correct `ontobio-parse-assocs.py` command that we should be testing for this.

**Comment by mugitty** [comment]
@dustine32 - You are correct.  The update in required for [Makefile-gaf-reprocess](https://github.com/geneontology/go-site/blob/master/scripts/Makefile-gaf-reprocess) .  

You can review from https://github.com/geneontology/go-site/pull/2127

**Review by dustine32 — APPROVED** [review]
Ok, it took me a bit but I realized the "easiest" test of this change was to run Pascale's [test GAF](https://github.com/geneontology/go-site/blob/master/docs/gorules_test_errors.gaf) through `ontobio-parse-assocs.py` with the new param:
```
ontobio-parse-assocs.py -f gorules_test_errors.gaf -F gaf -o gorules_test_errors_valid.gaf -I all.gaferences.json --report-md gorules_test_errors-report.md --report-json gorules_test_errors-report.json -m ~/go/go-site/metadata --allow_paint -l all convert --to gaf -n 2.2
```
One of the [test lines](https://github.com/geneontology/go-site/blob/fe5452121d10b71264c0dc58dcf07e8813843167/docs/gorules_test_errors.gaf#L141C45-L141C59) for `GORULE:0000030` contains ref `GO_REF:0000045`, which should now be getting caught and reported (with a `WARNING`) because [it has](https://github.com/geneontology/go-site/blob/fe5452121d10b71264c0dc58dcf07e8813843167/metadata/gorefs/goref-0000045.md?plain=1#L4) `is_obsolete: True`. Indeed, it is warned. Confirmed that `master` branch doesn't give this `WARNING` so all good.

@mugitty Feel free to merge whenever.

**Pull request merged**
