### PR TITLE
fixed logging issues for alliance loader and genedescriptions integration

### PR DESCRIPTION
**Pull request by valearna**
This PR fixes the following logging issues that we experienced at the Alliance while using ontobio in the arg_loader project and in the genedescriptions python package:

1. Logging to 'root' prevents the logging level to be set for the whole ontobio module - setting it to \_\_name\_\_ for each submodules would make it easier to manage logging preferences for ontobio when imported into another project
2. Logging level INFO generates a lot of log lines (e.g., skipped lines in assocparser) and makes the logs unreadable - it would be useful to move these log lines to DEBUG

These are the changes included in this PR:

- loggers created using \_\_name\_\_ and not attached to 'root' to allow programs that import ontobio to change its global logging level
- logs for skipped lines in assocparser, for indexed terms in assocmodel, and ecomap strings in ecomap set to DEBUG level to avoid overwhelming logs
- switched from deprecated method 'logging.warn' to 'logging.warning'

### CODE REVIEW

**Comment by valearna** [comment]
any chances this PR will be merged before the upcoming Alliance release? Thanks

**Comment by sierra-moxon** [comment]
just putting in a bump for this PR to be incorporated sooner than later -- the logging is quite verbose and makes it a bit tricky to find real errors in downstream processes that uses this package. @dougli1sqrd Thanks in advance! :)

**Comment by kltm** [comment]
@valearna @sierra-moxon It looks like there are now a fair number of conflicts. Would it be possible to get this change set updated?

**Comment by valearna** [comment]
Thanks @kltm, I'll work on the conflicts

**Comment by kltm** [comment]
@valearna NP!
@dougli1sqrd Would you mind taking a look at this again as it moves forward?

**Comment by dougli1sqrd** [comment]
Yes! This is great, if we can resolve the conflicts then we can definitely merge. If you need any help, let me know!

**Comment by valearna** [comment]
The code is ready but I can't run the test locally: I'm getting errors also when running the tests on the clean master branch. I'll push the changes to see if the Travis integration test passes.

**Comment by valearna** [comment]
Tests passed and ready to merge @dougli1sqrd @kltm

**Comment by kltm** [comment]
@dougli1sqrd I'll leave this to your discretion, or we can let @deepakunni3 looks at it when he gets back in, depending on how much you think this changes things.

**Pull request merged**
