### PR TITLE
allowing unzipped upstream sources

### PR DESCRIPTION
**Pull request by dougli1sqrd**
If config `compression` field is empty, then we assume no compression.

### CODE REVIEW

**Comment by dougli1sqrd** [comment]
The test config for reactome to demonstrate the success:
```
id: reactome.gaf
   label: "reactome gaf file"
   description: "gaf file for reactome from Reactome - a curated knowledgebase of biological pathways"
   url: http://current.geneontology.org/annotations/reactome.gaf.gz
   type: gaf
   dataset: reactome
   submitter: reactome
   compression:
   source: https://reactome.org/download/current/gene_association.reactome
   entity_type:
   status: inactive
   species_code:
   taxa:
```
Note the blank compression.

**Comment by kltm** [comment]
https://github.com/geneontology/go-site/commit/7cbd3e444c17#commitcomment-32646156
@dougli1sqrd For the final product, we'll need to make sure that the final *-src.gaf.gz byproducts are compressed as well, not just copied.

**Comment by dougli1sqrd** [comment]
@kltm with my latest update uncompressed sources are now also zipped.

**Comment by kltm** [comment]
Talked with @dougli1sqrd , feeling good about this one.

**Pull request merged**
