### PR TITLE
For #2081 repair goid, with/from and extension before running gorule …

### PR DESCRIPTION
**Pull request by mugitty**
…suite

### CODE REVIEW

**Review by kltm — APPROVED** [review]
Looks good eyeballing it--I'll leave it to you and @dustine32 to determine the right time to merge and release.

Is there a test that was false that will now be true with this change?

**Comment by mugitty** [comment]
The test that was previously failing is part of the ones in @pgaudet's list.  I will add to gorule 6 test cases.

**Comment by dustine32** [comment]
@mugitty Thanks for fixing this! I can't think of any reason we needed the GO rules to run before the GO term obsolete repair so this should be good.

However, have you tried running Pascale's [tests](https://github.com/geneontology/go-site/blob/fe5452121d10b71264c0dc58dcf07e8813843167/scripts/rule-example-validation.sh#L7) in `go-site` (the `validate.py rule` command) to confirm this fixes the issue?

**Comment by mugitty** [comment]
@dustine32 , I ran it with Pascale's errors.gaf file and the validate.py rule. I want to add a test case where the GO id is fixed and checked by GORULE 6. I will let you know when it is ready

Thanks

**Comment by mugitty** [comment]
Code updated.  Please review

**Review by dustine32 — APPROVED** [review]
Went through these code changes with @mugitty. Tests all pass so we are good!

**Pull request merged**
