### PR TITLE
Issue 450 parse use association

### PR DESCRIPTION
**Pull request by dougli1sqrd**
This turns parsers and emitters to using GoAssociation.

For https://github.com/biolink/ontobio/issues/450

### CODE REVIEW

**Comment by kltm** [comment]
Given the amount of change, I'll be trusting what has done after testing.

**Comment by dougli1sqrd** [comment]
@kltm @dustine32 

The jenkins test for the refactor passes!
https://build.geneontology.org/job/geneontology/job/pipeline/job/ontobio-issue-450-2.0.0-pre0-test/6/

Does the data look okay on skyhook? How does the code look?

**Comment by dougli1sqrd** [comment]
MGI seems to have lots of syntax errors now with the stricter relation parsing: http://skyhook.berkeleybop.org/ontobio-issue-450-2.0.0-pre0-test/reports/mgi-report.html#gorule-0000001

I will add these relations to the known relations table in ontobio until we have a more sophisticated parse that uses RO and gorel ontologies.

**Comment by dustine32** [comment]
@dougli1sqrd Yeah, looks like a lot of them are just missing relations as you said. Though for something like `has_input(MGI:MGI:98813)`, the MGI "double-prefix" seems to be escaping your regex:
https://github.com/biolink/ontobio/blob/253ee8a194ca38df7efc3a181010ad8490519dd8/ontobio/model/association.py#L129
This would explain the higher error count in MGI.

**Comment by dustine32** [comment]
@dougli1sqrd How about this regex allowing multiple `ABC:` prefixes?
```
([\w]+)\(((\w+:)+[\w][\w\.]*)\)
```
https://regex101.com/r/Pa0qAb/1

**Comment by dougli1sqrd** [comment]
yep that's on its way :)

**Comment by dougli1sqrd** [comment]
```
dougli1sqrd@neighbor:~/lbl/tmp $ ls -l master/
total 859500
-rw-rw-r-- 1 dougli1sqrd dougli1sqrd 103493775 Aug 19 16:53 aspgd.gaf
-rw-rw-r-- 1 dougli1sqrd dougli1sqrd     14192 Aug 19 16:53 goa_chicken_complex.gaf
-rw-rw-r-- 1 dougli1sqrd dougli1sqrd  32601987 Aug 19 16:53 goa_chicken.gaf
-rw-rw-r-- 1 dougli1sqrd dougli1sqrd  22984354 Aug 19 16:53 goa_human_isoform.gaf
-rw-rw-r-- 1 dougli1sqrd dougli1sqrd      7569 Aug 19 16:53 goa_pig_complex.gaf
-rw-rw-r-- 1 dougli1sqrd dougli1sqrd  22907914 Aug 19 16:53 goa_pig.gaf
-rw-rw-r-- 1 dougli1sqrd dougli1sqrd  14843566 Aug 19 16:53 goa_pig_isoform.gaf
-rw-rw-r-- 1 dougli1sqrd dougli1sqrd   3825093 Aug 19 16:53 goa_pig_rna.gaf
-rw-rw-r-- 1 dougli1sqrd dougli1sqrd 563321009 Aug 19 16:17 goa_uniprot_all.gaf
-rw-rw-r-- 1 dougli1sqrd dougli1sqrd      3399 Aug 19 16:17 goa_uniprot_all_noiea.gaf
-rw-rw-r-- 1 dougli1sqrd dougli1sqrd  85077354 Aug 19 16:53 mgi.gaf
-rw-rw-r-- 1 dougli1sqrd dougli1sqrd  10253083 Aug 19 16:53 pombase.gaf
-rw-rw-r-- 1 dougli1sqrd dougli1sqrd    554398 Aug 19 16:53 pseudocap.gaf
-rw-rw-r-- 1 dougli1sqrd dougli1sqrd  20089157 Aug 19 16:53 wb.gaf
dougli1sqrd@neighbor:~/lbl/tmp $ ls -l ontobio-2.0.0/
total 859488
-rw-rw-r-- 1 dougli1sqrd dougli1sqrd 103493775 Aug 19 17:14 aspgd.gaf
-rw-rw-r-- 1 dougli1sqrd dougli1sqrd     14192 Aug 19 17:14 goa_chicken_complex.gaf
-rw-rw-r-- 1 dougli1sqrd dougli1sqrd  32601987 Aug 19 17:14 goa_chicken.gaf
-rw-rw-r-- 1 dougli1sqrd dougli1sqrd  22984354 Aug 19 17:14 goa_human_isoform.gaf
-rw-rw-r-- 1 dougli1sqrd dougli1sqrd      7569 Aug 19 17:14 goa_pig_complex.gaf
-rw-rw-r-- 1 dougli1sqrd dougli1sqrd  22907914 Aug 19 17:14 goa_pig.gaf
-rw-rw-r-- 1 dougli1sqrd dougli1sqrd  14843566 Aug 19 17:14 goa_pig_isoform.gaf
-rw-rw-r-- 1 dougli1sqrd dougli1sqrd   3825093 Aug 19 17:14 goa_pig_rna.gaf
-rw-rw-r-- 1 dougli1sqrd dougli1sqrd 563321009 Aug 19 16:35 goa_uniprot_all.gaf
-rw-rw-r-- 1 dougli1sqrd dougli1sqrd      3399 Aug 19 16:35 goa_uniprot_all_noiea.gaf
-rw-rw-r-- 1 dougli1sqrd dougli1sqrd  85062312 Aug 19 17:14 mgi.gaf
-rw-rw-r-- 1 dougli1sqrd dougli1sqrd  10253125 Aug 19 17:14 pombase.gaf
-rw-rw-r-- 1 dougli1sqrd dougli1sqrd    554398 Aug 19 17:14 pseudocap.gaf
-rw-rw-r-- 1 dougli1sqrd dougli1sqrd  20089157 Aug 19 17:14 wb.gaf
```

The file sizes from the ontobio-2.0.0 test run compared to master show that only mgi and pombase have differences in file sizes. Likely this is due to slightly stricter and different way extension relations are parsed. I'll continue looking.

**Comment by dougli1sqrd** [comment]
From conversation with @kltm:
```
sjcarbon@moiraine:/tmp$:) cat wb-master.gaf | cut -f 6,8,16 | sed "s/|/\t/g" | sed 's/\,/\t/g' | sed 's/\t/\n/g' | sort | uniq -c | sort > wb-master-items.txt
sjcarbon@moiraine:/tmp$:) cat wb-branch.gaf | cut -f 6,8,16 | sed "s/|/\t/g" | sed 's/\,/\t/g' | sed 's/\t/\n/g' | sort | uniq -c | sort > wb-branch-items.txt
sjcarbon@moiraine:/tmp$:) diff wb-master-items.txt wb-branch-items.txt | wc -l
```

I'm also examining the combined reports of master and branch.

use jq commands:
1 will find error report objects (the offending part of the gaf) that are extensions with spaces in the filler
2 will find the same but where the filler has no ID separator `:`
```
cat reports/ontobio-2.0.0-combined.report.json | jq -c '.[] | select(.dataset == "mgi") | .messages | .["gorule-0000001"] | .[].obj' | grep --color -P '\(.*\s+.*\)'
cat reports/ontobio-2.0.0-combined.report.json | jq -c '.[] | select(.dataset == "mgi") | .messages | .["gorule-0000001"] | .[].obj' | grep --color -P '\(\w+[^:]\)'
```

**Comment by dougli1sqrd** [comment]
Talking with David Hill about the mgi reports and errors, he was satisfied that the reports were correct. I'll check with Pombase next.

**Comment by dougli1sqrd** [comment]
Looking through pombase, they are actually the same. The difference in file size I think is more due to reordering of the `References` field. Additionally, there are changes in the `with/from` column which are from properly parsing commas vs pipes in that field. So this appears more correct. I compared pombase source to our new output, and commas are correctly being retained (instead of converted into pipes, as in master).

Doing the `pombase-items.txt` trick above like with mgi, I see they are identical, so they have same counts of each symbol in `withfrom`, `references`, and `extensions`. This all makes me confident that actually pombase is the same.

And so, in conclusion, it seems that all datasets have the same data in the refactor, accounting for the differences in MGI.

I say we either lift to snapshot, or merge to master. I think we could manage to just merge, but I'll wait for other opinions, @kltm @dustine32.

**Comment by kltm** [comment]
Worst case scenario for the GO is that we back out of this new version of ontobio, correct? With that, and the general satisfaction of the reports, I think it's probably safe to move ahead. @dustine32 ?

**Comment by dustine32** [comment]
@dougli1sqrd Yeah, with your analysis it's pretty convincing that nothing dramatic has changed in the output. It's awesome that those commas in the with/from field aren't getting squashed anymore.

**Comment by dougli1sqrd** [comment]
@kltm found a weird line in pombase:
```
PomBase SPBC1289.03c    spi1            GO:0005515      PMID:18422602   IPI     PomBase:SPAC25A8.01c    F       Ran GTPase Spi1         protein taxon:4896
      20080718        PomBase         Error(info='Identity of CURIE is empty', entity='')
```
I will find and fix the bug

**Comment by dougli1sqrd** [comment]
Okay, produced a fix and a test. Basically that ID was being converted into a Curie and failed, but the error was just  passed along instead of caught.

**Comment by dougli1sqrd** [comment]
I found differences in only 5 files:
dictybase, goa_human_rna, goa_human, mgi, and pombase.

All other files have identical file sizes.

From the earlier runs, we can account for, and are satisfied with the differences in mgi and pombase.

So, looking at dictybase, goa_human_rna, and goa_human, it appears that the only differences are swapping orders of identifiers in certain fields that don't change the meaning (like withfrom, etc). The branch files are also smaller by just a few lines. The lines that are filtered in the test branch that were kept in snapshot were all relations that ontobio did not know about.

The most recent commits add the few missing relations to ontobio and those lines should be kept. No other anomalies were detected.

**Comment by kltm** [comment]
@dougli1sqrd Sounds like thorough testing to me.
@dustine32 Any thoughts before this goes in?

**Comment by dougli1sqrd** [comment]
@kltm Before we merge, let me know I'll set the version to `2.0.0` removing the pre-release suffix.

**Comment by dustine32** [comment]
@kltm Sorry just noticed this now. Yep, @dougli1sqrd's explanation seems correct and would account for those lines being either dropped or have column values shuffled.

**Pull request merged**
