### PR TITLE
Update README-developers.md

### PR DESCRIPTION
**Pull request by deepakunni3**
Just clarifying the steps needed to make a new Ontobio release.

### CODE REVIEW

**Comment by dougli1sqrd** [comment]
This looks good! Just out of curiosity though, why would the local checked out version ever be different than what's on pypi?

**Comment by deepakunni3** [comment]
Because it was. That's why I ended up skipping `1.19.1`.
The local checkout version was `1.19.1` and I assumed it was already released, and bumped it again to `1.19.2` when in reality PyPI was at `1.19.0`

**Comment by dougli1sqrd** [comment]
oh weird, did I mess something up? Master should have had the right version.

**Comment by deepakunni3** [comment]
Looking back at the commits, it looks like Dustin bumped the version as part of a PR: https://github.com/biolink/ontobio/commit/a15975e76ad713e7650081c36253c9d9e08b5627#diff-5ce3cf331b5fc020557daa5b57bfcea8

I didn't realize that when I merged the PR. So when I bumped, it ended up to be a double bump.

It's all good 👍

**Pull request merged**
