### PR TITLE
For #2064 - Added check for pipe in gene symbol

### PR DESCRIPTION
**Pull request by mugitty**
For #2064 - gorule-0000001 check for pipe in gene symbol

### CODE REVIEW

**Review by kltm — COMMENTED** [review]
Has test, so I'm good. I'll leave merge to @dustine32

**Comment by dustine32** [comment]
Linking to https://github.com/geneontology/go-site/issues/2064

**Comment by dustine32** [comment]
Yep @mugitty this looks good to me. Have you confirmed it works with @pgaudet's new test line here?: https://github.com/geneontology/go-site/pull/2174

**Comment by mugitty** [comment]
@dustine32 , Thanks for checking.  I ran it against the errors.gaf file.  Output in errors json file for pipe in gene symbol is as follows:
            {
                "level": "ERROR",
                "line": "UniProtKB\tA1B2F4\tazt|D\tacts_upstream_of_or_within_negative_effect\tGO:0005634\tPMID:26468286\tIDA\t\tC\tGORULE_TEST:0000001-18\t\tprotein\ttaxon:318586\t20230427\tPomBase\t",
                "type": "Invalid symbol",
                "message": "Pipes are not allowed in gene symbol",
                "obj": "GO:0005634",
                "taxon": "taxon:318586",
                "rule": 1
            },

**Review by dustine32 — APPROVED** [review]
@mugitty Thanks for confirming. Just wanted to make sure the go-site tests would run successfully.

**Pull request merged**
