### PR TITLE
Association collections

### PR DESCRIPTION
**Pull request by dougli1sqrd**
This is the bit that will help thread through arbitrary Annotation data along with Bio Entity data. Drawing when the three of us talked about this: https://docs.google.com/drawings/d/1QSurx_SG50LXUpVRUYZVWNkSF8szGrGh5DpBtXRzKGo/edit

### CODE REVIEW

**Comment by kltm** [comment]
Excitement!

**Comment by dustine32** [comment]
@dougli1sqrd Oh right, I suppose the same code change could apply to `master` right now. Should I make a separate branch and PR to `master` for this?

**Comment by dougli1sqrd** [comment]
Yeah I imagine we should. This could show up in the current world now, so let's separate it out.

**Comment by dougli1sqrd** [comment]
Okay, this is a real PR now!

**Comment by kltm** [comment]
@dougli1sqrd What does the "risk profile" look like to you? Should this go in before the next release attempt?

**Comment by dougli1sqrd** [comment]
Low risk, but we should probably go ahead and wait for the release to make an ontobio release and bump go-site. I think we'd be safe to merge to master though.

**Comment by kltm** [comment]
What he sez.

**Pull request merged**
