### PR TITLE
[WIP] refactored assoc extension datamodel, #135

### PR DESCRIPTION
**Pull request by cmungall**

### CODE REVIEW

**Comment by cmungall** [comment]
model is now disjunctive normal form. Previously was list of rel expressions. Now a dict, top level keyed by union_of, which is a list of expressions to be ORed. Each such expression is an object keyed by intersection_of, which is a list of expressions to be ANDed

This now reflects the complete expression in the gaf, for grammar see appendix of http://doi.org/10.1186/1471-2105-15-155

example

```
'union_of': [
   {'intersection_of':[ 
       {property:P1, filler:F1},
        ...
      ]
    },
    ...
]
```

**Comment by cmungall** [comment]
shall we go ahead and merge this?

**Comment by dougli1sqrd** [comment]
sure. Have we looked at the rdf portion? I can run some rdf generation too

**Comment by dougli1sqrd** [comment]
Yeah let's merge this. I'll perform another ontobio release

**Pull request merged**
