### PR TITLE
qualifiers from gpad to gaf that are outside the gaf spec just blank out the field

### PR DESCRIPTION
**Pull request by dougli1sqrd**
For https://github.com/biolink/ontobio/issues/470

### CODE REVIEW

**Review by dustine32 — APPROVED** [review]
@dougli1sqrd Yep, this is what I did to get my GPAD->GAF2.1 converter to work, though I was working with the `GoAssociation.to_gaf_2_1_tsv` function. Thanks for getting at this!

**Comment by kltm** [comment]
@dougli1sqrd I just want to particularly confirm the case of GAF 2.2 -> GAF 2.1.

**Comment by dougli1sqrd** [comment]
@dustine32 yeah this change was done off master, so that's why it's different. We'll have to merge the changes over into the the branch you're using.

@kltm I can write a test for that.

**Comment by dougli1sqrd** [comment]
Test for gaf 2.2 -> gaf 2.1 qualifier done

**Comment by kltm** [comment]
Looks good to me.

**Review by kltm — APPROVED** [review]

**Pull request merged**
