### PR TITLE
ontobio now respects gaf 2.2 and parses qualifiers dependent on versions

### PR DESCRIPTION
**Pull request by dougli1sqrd**

### CODE REVIEW

**Comment by kltm** [comment]
Is this it?! Sweet!
I'm assuming that one test with qualifiers and no version barfs, yes?
Otherwise, this is terrific...and out of an abundance of caution let's merge it after the next release.

**Comment by dougli1sqrd** [comment]
The test with no version will just default to gaf 2.1. Essentially anything that isnt' gaf 2.2 will default to 2.1, since 2.1 is a superset of all other previous versions

**Comment by dougli1sqrd** [comment]
For https://github.com/biolink/ontobio/issues/446

**Comment by dougli1sqrd** [comment]
@kltm So the gaf writer now skips lines that don't comform, writing an error message.

**Comment by kltm** [comment]
Okay, great. As from the email, this is not expected to be an issue, but we'll want to make sure that there is documentation for other users. Would documentation go with this PR, or elsewhere?

**Comment by dougli1sqrd** [comment]
I'm not sure. Maybe in any existing pipeline documentation we could talk about gaf 2.2 and now what the parser does.

**Comment by kltm** [comment]
I'm more thinking for somebody trying to use ontobio--the fact that annotation would be "lost" in conversion should just be mentioned somewhere public.

**Comment by dougli1sqrd** [comment]
ah okay, sure. 

We don't actually have much documentation for ontobio as far as I know. I think there is a website. 

But I could write a docstring in the GafWriter code directly that explains how that works.

**Comment by kltm** [comment]
If there's nothing else, for now that would be the place to start--the only place where somebody could go.

**Comment by dougli1sqrd** [comment]
Updated documentation for GafWriter explaining the version conditions for which a line could be skipped.

**Pull request merged**
