### PR TITLE
Emit providedBy to all individuals; for geneontology/gocamgen#89

### PR DESCRIPTION
**Pull request by dustine32**
Fixes an issue where "Assigned By" isn't appearing for MOD import annotations in ART or Noctua Form.

### CODE REVIEW

**Comment by kltm** [comment]
Single to list, looks good to me. In general, are there tests for these kinds of things?

**Comment by kltm** [comment]
@dustine32 Cannot link through to issue through title geneontology/gocamgen#89

**Review by kltm — APPROVED** [review]

**Comment by dustine32** [comment]
@kltm Thanks for fixing the link, I forgot it won't do it automatically through the title.

For tests, I used to have them for things like this on the old gocamgen repo, where I made the model in `rdflib.graph` and then SPARQL'ed out what I was looking for. But the startup cost for generating a model has become >10 sec. Maybe I can strip down the process a bit.

**Comment by kltm** [comment]
Something to pick at anyways at some point. Or something.
I'm not sure if you actually want feedback from both of us; feel free to merge.

**Review by dougli1sqrd — APPROVED** [review]

**Pull request merged**
