### PR TITLE
lots of changes to append any existing noctua models gpads to a group…

### PR DESCRIPTION
**Pull request by dougli1sqrd**
… dataset

### CODE REVIEW

**Comment by kltm** [comment]
WIP?

**Comment by dougli1sqrd** [comment]
Tests pass now. I'll make a corresponding change to add the noctua config yaml.

**Comment by kltm** [comment]
Before triggering, we'll need to talk to the consumers and make sure they're ready. E.g. @ukemi
Let's wait (at least) until after this release.

**Comment by dougli1sqrd** [comment]
ah okay. Cool.

**Pull request merged**
