### PR TITLE
Moving biolink scigraph to ontobio, owlsim improvements

### PR DESCRIPTION
**Pull request by kshefchek**
Originally my goal was to work on https://github.com/biolink/biolink-api/issues/380, I'm expanding this PR to completely decouple any logic dealing with backend services from the biolink-api codebase, specifically:

- [x] clean out and rewrite our autogen'ed data classes (from marshmallow) to standard dataclasses (eg https://github.com/biolink/biolink-api/blob/master/biomodel/core.py)
- [x] rewrite other data style classes as proper dataclasses (a lot of these were written before dataclasses existed)
- [ ] ~~Allow biolink-api to configure ontobio services without creating a yaml file and moving it to the proper virtual environment directory within ontobio~~
- [ ] ~~Clean up the owlsim code so that caching calls does not block biolink-api start up~~
- [x] https://github.com/biolink/biolink-api/issues/380

EDIT: going to come back to tasks 3 and 4 in another PR

### CODE REVIEW

**Comment by dustine32** [comment]
@kshefchek Crazy. These test errors are due to an upstream mapping change by @nsuvarnaiari in [evidenceontology/evidenceontology/gaf-eco-mapping.txt](https://raw.githubusercontent.com/evidenceontology/evidenceontology/master/gaf-eco-mapping.txt) (see this [diff](https://github.com/evidenceontology/evidenceontology/commit/2399858248527b6a29642870d230d2f7b37b5043#diff-8026d95055ee94ddd11aee9f5a7b6509f2153da1defe2b9c5dad33e597beb78d)) that changed the old default mapping `IEA-> ECO:0000501` to `IEA -> ECO:0007669`. The file is consumed here:
https://github.com/biolink/ontobio/blob/d703b9110b6660049c26dc4edb1278ce656ee216/ontobio/ecomap.py#L29
Unfortunately, the currently failing tests deal with IEAs and `ECO:0000501` is hard-coded:
https://github.com/biolink/ontobio/blob/d703b9110b6660049c26dc4edb1278ce656ee216/ontobio/io/qc.py#L241
https://github.com/biolink/ontobio/blob/d703b9110b6660049c26dc4edb1278ce656ee216/ontobio/io/qc.py#L269
https://github.com/biolink/ontobio/blob/d703b9110b6660049c26dc4edb1278ce656ee216/ontobio/io/qc.py#L447

Not certain of the best way to fix this, so @cmungall @kltm @nsuvarnaiari, I'm guessing this upstream ECO mapping change will affect IEAs in the release pipeline. Should this be addressed upstream (revert the `gaf-eco-mapping.txt` change) or do we adjust our `ontobio` code to expect `IEA -> ECO:0007669`?

**Comment by nsuvarnaiari** [comment]
Hi @dustine32 

Yes, we are now mapping IEA to ECO:0007669 in our gaf-eco-mapping.txt. I cannot tell what is the right thing to do at your end, but adjusting ontobio code to expect IEA ->ECO:0007669 seems the correct way.

Thanks,
Suvvi

**Comment by mgiglio99** [comment]
Hello,
Sorry this change has caused problems for your system.
The recent change of mapping of GO evidence code IEA to ECO:0007669 came about due to concerns raised by GO regarding the scope of what was included under ECO:0000501. Please see ECO issue https://github.com/evidenceontology/evidenceontology/issues/251 for details on that.

Regarding the lines of code above, we suggest: 
for line 447, you change it to iea = "ECO:0007669",
for line 269, we suggest adding ECO:0007669 to the set of non-experimental terms, but leaving ECO:0000501 there for now, since it is likely many people are still using it
for line 241, we are not sure if just changing to ECO:0007669 is sufficient since we don't know what's in self.do_not_manually_annotate and just saying that a term is not ECO:0007669 is not enough to say that it's manually curated.

Happy to discuss more as needed to get this sorted out.
Michelle

**Comment by dustine32** [comment]
Thank you @mgiglio99 and @nsuvarnaiari for the explanation! Right, we'll adjust our code to expect the new IEA to ECO:0007669 mapping, i.e. ensure `ontobio` code always pulls the `IEA`->`ECO` code mapping from your `gaf-eco-mapping.txt` (via the PURL).

@kshefchek I can make these changes in a separate PR (this should fix the tests too), merge to `master`, double-check this PR's tests run fine and then I'll approve. Thanks for your patience!

**Comment by kshefchek** [comment]
thanks @nsuvarnaiari and @mgiglio99! :) @dustine32 that plan sounds good to me, I'll wait for https://github.com/biolink/ontobio/pull/590 to be merged and then pull in those changes.

**Review by dustine32 — APPROVED** [review]
Thanks @kshefchek! I just pushed a merge conflict (from a change I made) fix while testing the `master` merge into your branch.

Feel free to merge at your convenience!

**Pull request merged**
