### PR TITLE
Go site 2246 gorule 0000001 rnac rna types are getting mangled

### PR DESCRIPTION
**Pull request by mugitty**

### CODE REVIEW

**Comment by kltm** [comment]
Noting geneontology/go-site#2246

**Comment by kltm** [comment]
@mugitty Should I wait until the tests pass for review?

**Comment by mugitty** [comment]
> @mugitty Should I wait until the tests pass for review?

Please wait until tests pass

**Comment by dustine32** [comment]
@mugitty Cool, looks like you fixed the tests! That failing `tests/unit/test_clinical_mod.py` test was [removed](https://github.com/biolink/ontobio/commit/b0e7bdd2719fba8f126a189eada5454fa0e5e8bb) from `travis_test` on `master` a few months ago so definitely wasn't your code's fault.

**Comment by mugitty** [comment]
@dustine32, I had to merge the updates from master

Thanks

**Comment by mugitty** [comment]
@kltm and @dustine32 I have updated the CURIE lookup table with latest updates requested by @pgaudet and restored previous updates to tests.  Please review

**Review by dustine32 — APPROVED** [review]
@mugitty Approved!

This matches what the issue https://github.com/geneontology/go-site/issues/2246 asks for and the tests all pass. We can confirm this change's effects on a pipeline run.

**Comment by pgaudet** [comment]
Great! Can we now have a list of the entity types that fail ? (ideally by group - ie 'assigned by')

**Pull request merged**
