### PR TITLE
Go site 1453 gpad 2 parser

### PR DESCRIPTION
**Pull request by dougli1sqrd**

### CODE REVIEW

**Comment by dougli1sqrd** [comment]
For partial fulfillment of https://github.com/geneontology/go-site/issues/1453

**Review by kltm — COMMENTED** [review]
Would it be possible to also get a non-MGI test set, or maybe that's there but not in the diff?

**Comment by kltm** [comment]
I took a look and it seems to be about what I might expect. Is there an emitter associated with this?

**Comment by dougli1sqrd** [comment]
Yeah, I think in master we have an emitter currently, but again, nothing is "hooked up" to the outside world. But this lets us make a command line tool or modify existing tools.

Can you clarify more on your "non MGI test set" comment? Included in this PR are unit tests of small scale functionality, but probably modifying/creating command line parsing tools that can do gpad 2 in and out maybe in a small pipeline might be a better test?

**Review by dustine32 — APPROVED** [review]

**Pull request merged**
